// Generated by CoffeeScript 1.6.3
(function() {
  var NodeTree;

  NodeTree = (function() {
    NodeTree.getInstance = function() {
      return new NodeTree();
    };

    function NodeTree() {
      this.NodeArray = {};
      this.is_end = false;
      return;
    }

    NodeTree.prototype.setNode = function(value, subNode) {
      this.NodeArray[value] = subNode;
    };

    NodeTree.prototype.getNode = function(value) {
      return this.NodeArray[value];
    };

    NodeTree.prototype.setEnd = function(val) {
      this.is_end = val;
    };

    NodeTree.prototype.isEnd = function() {
      return this.is_end;
    };

    NodeTree.prototype.getNodeArray = function() {
      return this.NodeArray;
    };

    return NodeTree;

  })();

  module.exports = NodeTree;

}).call(this);
