// Generated by CoffeeScript 1.8.0

/*
 * test for filter
 */

(function() {
  var array, fs, keyword_filter, should, str1, str2, str3, str4, strs;

  should = require("should");

  keyword_filter = require("../keyword_filter");

  fs = require("fs");

  array = ['sM', '大小', '枪支', '枪', 'a', '枪支弹药', '大人'];

  keyword_filter.init(array);

  str1 = 'afadfaSmsmsM, dadfafd大小大人大的强制枪支枪支弹药手枪';

  str2 = '枪支枪支弹药枪afbadakfja8sm阿达撒开了房哈覅大小人';

  str3 = 'asfdja adfja;skf dsafowre较大；烧开后覅回复哈的骄傲饭卡地方发大水发回复哈佛';

  str4 = 'dsgfsdtresfdrnemr较大；烧开后覅回复哈的骄傲饭卡地方发大水发回复哈佛';

  strs = ['枪', str1, str2, str3, str4];

  describe("test keyword_filter", function() {
    before(function() {});
    describe("checksum", function() {
      it("keyword_filter isContainKeyword", function(done) {
        strs.map(function(str) {
          return console.log(keyword_filter.isContainKeyword(str));
        });
        return done();
      });
      it("keyword_filter replaceKeyword", function(done) {
        strs.map(function(str) {
          console.log(str);
          return console.log(keyword_filter.replaceKeyword(str, false));
        });
        return done();
      });
      it("keyword_filter replaceStrKeyword", function(done) {
        strs.map(function(str) {
          console.log(str);
          return console.log(keyword_filter.replaceStrKeyword(str, false));
        });
        return done();
      });
      return it("keyword_filter calcCount", function(done) {
        strs.map(function(str) {
          console.log(str);
          return console.log(keyword_filter.calcCount(str, false));
        });
        return done();
      });
    });
    return describe("effciency test", function() {
      it("keyword_filter isContainKeyword", function(done) {
        var data, start;
        data = fs.readFileSync('../../files/test1.txt', "utf8");
        console.log(data.length);
        start = Date.now();
        console.log(keyword_filter.isContainKeyword(data));
        console.log(" times: " + (Date.now() - start));
        return done();
      });
      it("keyword_filter replaceKeyword", function(done) {
        var data, start, str;
        data = fs.readFileSync('../../files/test1.txt', "utf8");
        console.log(data.length);
        start = Date.now();
        str = keyword_filter.replaceKeyword(data);
        console.log(str);
        console.log(" times: " + (Date.now() - start));
        return done();
      });
      it("keyword_filter replaceStrKeyword", function(done) {
        var data, start, str;
        data = fs.readFileSync('../../files/test1.txt', "utf8");
        console.log(data.length);
        start = Date.now();
        str = keyword_filter.replaceStrKeyword(data);
        console.log(" times: " + (Date.now() - start));
        return done();
      });
      return it("keyword_filter calcCount", function(done) {
        var count, data, start;
        data = fs.readFileSync('../../files/test1.txt', "utf8");
        console.log(data.length);
        start = Date.now();
        count = keyword_filter.calcCount(data);
        console.log(count);
        console.log(" times: " + (Date.now() - start));
        return done();
      });
    });
  });

}).call(this);
